version: '3.9'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - ./db/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  api:
    image: node
    container_name: api
    restart: always
    depends_on:
     - mongo
    ports:
      - 3000:3000
    volumes: 
      - ./api:/api
    entrypoint: ["/bin/bash", "-c" , "cd /api && npm start"]
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/