# Generated by Django 3.2.12 on 2022-02-14 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('last_time_check', models.DateField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PTIid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.CharField(max_length=30)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('registration', models.IntegerField()),
                ('expire_date', models.DateField()),
                ('rfid_uid', models.UUIDField(blank=True, help_text='Unique Identifier of the member RFID Tag', unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TCS.user')),
            ],
        ),
    ]
