# Generated by Django 3.2.12 on 2022-02-14 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TCS.user')),
            ],
        ),
    ]
