# Generated by Django 3.2.12 on 2022-02-14 08:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0002_timecheck'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ptiid',
            options={'verbose_name': 'Crachá'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='ptiid',
            name='affiliation',
            field=models.CharField(choices=[('UNIOESTE', 'Unioeste Estadual do Oeste do Paraná'), ('UNILA', 'Universidade Federal da Integração Latino-Americana'), ('FPTI', 'Fundação Parque Tecnológico de Itaipu'), ('OTHER', 'Outro')], help_text='Instituição ao qual o usuário é afiliado', max_length=50, verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='ptiid',
            name='expire_date',
            field=models.DateField(help_text='Data de validade do crachá de identificação', verbose_name='Validade'),
        ),
        migrations.AlterField(
            model_name='ptiid',
            name='registration',
            field=models.CharField(help_text='Número de matrícula do usuário no PTI', max_length=7, validators=[django.core.validators.RegexValidator(code='Número Inválido', message='A matrícula precisa ser exatamente como no crachá', regex='^[0-9]{7,7}$')], verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='ptiid',
            name='rfid_uid',
            field=models.UUIDField(blank=True, help_text='Unique Identifier do chip RFID do crachá do usuário', unique=True, verbose_name='UID do Crachá'),
        ),
        migrations.AlterField(
            model_name='ptiid',
            name='role',
            field=models.CharField(blank=True, help_text='Qual o cargo do usuário no LabIoT', max_length=50, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=250, verbose_name='Primeiro Nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=250, verbose_name='Último Nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_time_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TCS.timecheck'),
        ),
    ]
