# Generated by Django 3.2.12 on 2022-02-14 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0003_auto_20220214_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_time_check',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='TCS.timecheck'),
        ),
    ]
