# Generated by Django 3.2.12 on 2022-02-14 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0004_alter_user_last_time_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_time_check',
        ),
    ]
