# Generated by Django 3.2.12 on 2022-02-14 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TCS', '0005_remove_user_last_time_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptiid',
            name='rfid_uid',
            field=models.CharField(blank=True, help_text='Unique Identifier do chip RFID do crachá do usuário', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='UID Inválido', message='Digite no formato com letras maiúsculas (0x:0x:0x:0x)', regex='^([0-9A-F]{2}):([0-9A-F]{2}):([0-9A-F]{2}):([0-9A-F]{2})$')], verbose_name='UID do Crachá'),
        ),
    ]
